################################################
# Copyright 2019, Verizon Media.
# Licensed under the Apache License, Version 2.0
# See LICENSE file in project root for terms.
################################################

elide:
  modelPackage: 'example.models'
  json-api:
    path: /api/v1
    enabled: true
  graphql:
    path: /graphql/api/v1
    enabled: true
  swagger:
    path: /doc
    enabled: true
  async:
    enabled: true
    threadPoolSize: 7
    maxRunTime: 65
    cleanupEnabled: true
    queryCleanupDays: 7
    defaultAsyncQueryDAO: true
  dynamic-config:
    enabled: true
    path: src/main/resources/models

spring:
  main:
    allow-bean-definition-overriding: true
  application:
    name: Elide
  jpa:
    open-in-view: false
    hibernate:
      show_sql: true
      naming:
        physical-strategy: 'org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl'
      dialect: 'org.hibernate.dialect.H2Dialect'
      ddl-auto: 'validate'
      jdbc:
        use_scrollable_resultset: true
  datasource:
    url: 'jdbc:h2:mem:db1;DB_CLOSE_DELAY=-1'
    username: 'sa'
    password: ''
    driver-class-name: 'org.h2.Driver'
  liquibase:
    change-log: 'classpath:db/changelog/changelog.xml'
    enabled: true
  secondary-datasource:
    url: 'jdbc:h2:mem:db2;DB_CLOSE_DELAY=-1'
    username: 'sa1'
    password: ''
    driver-class-name: 'org.h2.Driver'
  secondary-liquibase:
    change-log: 'classpath:db/changelog/secondary_changelog.xml'
    enabled: true

server:
  port: 8080

logging:
  path: /tmp

security:
  origin: "*"

---

spring:
  profiles: production
  jpa:
    hibernate:
      show_sql: true
      naming:
        physical-strategy: 'org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl'
      dialect: 'org.hibernate.dialect.PostgreSQLDialect'
      ddl-auto: 'validate'
      jdbc:
        use_scrollable_resultset: true
  datasource:
    url: ${JDBC_DATABASE_URL}
    username: ${JDBC_DATABASE_USERNAME}
    password: ${JDBC_DATABASE_PASSWORD}
    driver-class-name: 'org.postgresql.Driver'
  liquibase:
    change-log: 'classpath:db/changelog/changelog.xml'
server:
  port: ${PORT}

security:
  origin: ${HOST}
